# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20181210_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
