# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20181211_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='works'),
        ),
    ]
