# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologie',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.Category'),
            preserve_default=False,
        ),
    ]
